spring.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:testdb

server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: VehiclesAPI
  profiles:
    active: dev
  h2:
    console:
      enabled: true

spring.jpa:
  hibernate.ddl-auto: create-drop
